### ISSUE TITLE
Request: line numbers

### ISSUE THREAD

**Issue by RSully** [nobuhito/atom-export-html#2]

**Comment by RSully** [comment]
Thank you!

However, looks kind of weird with line wrapping (I guess line wrapping in general looks weird to me).

**Comment by nobuhito** [comment]
@RSully Is it a problem of indentation ?

**Comment by RSully** [comment]
Yes I think so. Maybe spacing between numbers and code too.

**Comment by nobuhito** [comment]
@RSully What do you think?

![export-html-wrap](https://cloud.githubusercontent.com/assets/45220/11998914/01ee2206-aaf6-11e5-9a00-a558051abb43.png)

**Comment by RSully** [comment]
That's a good improvement
