### ISSUE TITLE
Problems with the Haskell highlighter

### ISSUE THREAD

**Issue by Valdsonjr** [nobuhito/atom-export-html#6]
Before writing this issue I used the stand-alone highlight.js (downloaded here: https://highlightjs.org/download/) with this file:
[htmltest.txt](https://github.com/nobuhito/atom-export-html/files/211436/htmltest.txt)

and it seems to be working just fine, as you can see here: 
![printscreen-cut](https://cloud.githubusercontent.com/assets/6580116/14405869/e91be21e-fe6e-11e5-9992-3e4c09ccabd4.png)

but when I try to generate the pdf with your plugin I get this:
[vs.pdf](https://github.com/nobuhito/atom-export-html/files/211437/vs.pdf)

maybe you're using an old version of highlight.js that has a bug?

OBS: I tried with C++ and Haskell, but only the Haskell version is wrong.
OBS2: Both versions use vs.css

**Comment by nobuhito** [comment]
@Valdsonjr  Please try v.3.0.0
