### ISSUE TITLE
Make tab-size configurable

### ISSUE THREAD

**Issue by ClaesBas** [nobuhito/atom-export-html#7]
Thanks for a nice plugin!
But go code gets uggly/unstandard with tab-size 8!

TIA
/Claes

**Comment by OiYouYeahYou** [comment]
I've just made a [pull request](https://github.com/nobuhito/atom-export-html/pull/8) with that enables this.

If it doesn't get pulled, copy the [code from here](https://github.com/nobuhito/atom-export-html/pull/8/commits/2b98ca856961f640540ba76e9b449273189535a4) by:

1. Open settings
2. Click "Open Config Folder" at the bottom of the left pane
3. In the folder pane, navigate to .atom > packages > export-html
4. Copy the relevant code into the files
5. Restart Atom

Then you can edit your preferred width in the package settings
